//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WooService.AXServices.AIFCrearPedidos
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
    public partial class CallContext : object
    {
        
        private string CompanyField;
        
        private string LanguageField;
        
        private string LogonAsUserField;
        
        private string MessageIdField;
        
        private string PartitionKeyField;
        
        private System.Collections.Generic.Dictionary<string, string> PropertyBagField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company
        {
            get
            {
                return this.CompanyField;
            }
            set
            {
                this.CompanyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogonAsUser
        {
            get
            {
                return this.LogonAsUserField;
            }
            set
            {
                this.LogonAsUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId
        {
            get
            {
                return this.MessageIdField;
            }
            set
            {
                this.MessageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey
        {
            get
            {
                return this.PartitionKeyField;
            }
            set
            {
                this.PartitionKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> PropertyBag
        {
            get
            {
                return this.PropertyBagField;
            }
            set
            {
                this.PropertyBagField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class AifFault : object
    {
        
        private string CustomDetailXmlField;
        
        private WooService.AXServices.AIFCrearPedidos.FaultMessageList[] FaultMessageListArrayField;
        
        private WooService.AXServices.AIFCrearPedidos.InfologMessage[] InfologMessageListField;
        
        private string StackTraceField;
        
        private int XppExceptionTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomDetailXml
        {
            get
            {
                return this.CustomDetailXmlField;
            }
            set
            {
                this.CustomDetailXmlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WooService.AXServices.AIFCrearPedidos.FaultMessageList[] FaultMessageListArray
        {
            get
            {
                return this.FaultMessageListArrayField;
            }
            set
            {
                this.FaultMessageListArrayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WooService.AXServices.AIFCrearPedidos.InfologMessage[] InfologMessageList
        {
            get
            {
                return this.InfologMessageListField;
            }
            set
            {
                this.InfologMessageListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int XppExceptionType
        {
            get
            {
                return this.XppExceptionTypeField;
            }
            set
            {
                this.XppExceptionTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessageList", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessageList : object
    {
        
        private string DocumentField;
        
        private string DocumentOperationField;
        
        private WooService.AXServices.AIFCrearPedidos.FaultMessage[] FaultMessageArrayField;
        
        private string FieldField;
        
        private string ServiceField;
        
        private string ServiceOperationField;
        
        private string ServiceOperationParameterField;
        
        private string XPathField;
        
        private string XmlLineField;
        
        private string XmlPositionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Document
        {
            get
            {
                return this.DocumentField;
            }
            set
            {
                this.DocumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentOperation
        {
            get
            {
                return this.DocumentOperationField;
            }
            set
            {
                this.DocumentOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WooService.AXServices.AIFCrearPedidos.FaultMessage[] FaultMessageArray
        {
            get
            {
                return this.FaultMessageArrayField;
            }
            set
            {
                this.FaultMessageArrayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field
        {
            get
            {
                return this.FieldField;
            }
            set
            {
                this.FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Service
        {
            get
            {
                return this.ServiceField;
            }
            set
            {
                this.ServiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperation
        {
            get
            {
                return this.ServiceOperationField;
            }
            set
            {
                this.ServiceOperationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperationParameter
        {
            get
            {
                return this.ServiceOperationParameterField;
            }
            set
            {
                this.ServiceOperationParameterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XPath
        {
            get
            {
                return this.XPathField;
            }
            set
            {
                this.XPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlLine
        {
            get
            {
                return this.XmlLineField;
            }
            set
            {
                this.XmlLineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlPosition
        {
            get
            {
                return this.XmlPositionField;
            }
            set
            {
                this.XmlPositionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessage", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public partial class InfologMessage : object
    {
        
        private WooService.AXServices.AIFCrearPedidos.InfologMessageType InfologMessageTypeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WooService.AXServices.AIFCrearPedidos.InfologMessageType InfologMessageType
        {
            get
            {
                return this.InfologMessageTypeField;
            }
            set
            {
                this.InfologMessageTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    public partial class FaultMessage : object
    {
        
        private string CodeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessageType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderService")]
    public interface triAIFCreateSalesQuotationOrderService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/triAIFCreateSalesQuotationOrderService/AIFCreateSalesQuotation" +
            "", ReplyAction="http://tempuri.org/triAIFCreateSalesQuotationOrderService/AIFCreateSalesQuotation" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(WooService.AXServices.AIFCrearPedidos.AifFault), Action="http://tempuri.org/triAIFCreateSalesQuotationOrderService/AIFCreateSalesQuotation" +
            "AifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFCreateSalesQuotationResponse> AIFCreateSalesQuotationAsync(WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFCreateSalesQuotationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/triAIFCreateSalesQuotationOrderService/AIFBorrarPedido", ReplyAction="http://tempuri.org/triAIFCreateSalesQuotationOrderService/AIFBorrarPedidoResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(WooService.AXServices.AIFCrearPedidos.AifFault), Action="http://tempuri.org/triAIFCreateSalesQuotationOrderService/AIFBorrarPedidoAifFault" +
            "Fault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFBorrarPedidoResponse> AIFBorrarPedidoAsync(WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFBorrarPedidoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/triAIFCreateSalesQuotationOrderService/AIFCreateSalesOrderWEB", ReplyAction="http://tempuri.org/triAIFCreateSalesQuotationOrderService/AIFCreateSalesOrderWEBR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WooService.AXServices.AIFCrearPedidos.AifFault), Action="http://tempuri.org/triAIFCreateSalesQuotationOrderService/AIFCreateSalesOrderWEBA" +
            "ifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFCreateSalesOrderWEBResponse> AIFCreateSalesOrderWEBAsync(WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFCreateSalesOrderWEBRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/triAIFCreateSalesQuotationOrderService/AIFCreateSalesOrder", ReplyAction="http://tempuri.org/triAIFCreateSalesQuotationOrderService/AIFCreateSalesOrderResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WooService.AXServices.AIFCrearPedidos.AifFault), Action="http://tempuri.org/triAIFCreateSalesQuotationOrderService/AIFCreateSalesOrderAifF" +
            "aultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFCreateSalesOrderResponse> AIFCreateSalesOrderAsync(WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFCreateSalesOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/triAIFCreateSalesQuotationOrderService/AIFFacturarPedidoVta", ReplyAction="http://tempuri.org/triAIFCreateSalesQuotationOrderService/AIFFacturarPedidoVtaRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WooService.AXServices.AIFCrearPedidos.AifFault), Action="http://tempuri.org/triAIFCreateSalesQuotationOrderService/AIFFacturarPedidoVtaAif" +
            "FaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        System.Threading.Tasks.Task<WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFFacturarPedidoVtaResponse> AIFFacturarPedidoVtaAsync(WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFFacturarPedidoVtaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="triAIFCreateSalesQuotationOrderServiceAIFCreateSalesQuotationRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class triAIFCreateSalesQuotationOrderServiceAIFCreateSalesQuotationRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public WooService.AXServices.AIFCrearPedidos.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _encabezado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _detalle;
        
        public triAIFCreateSalesQuotationOrderServiceAIFCreateSalesQuotationRequest()
        {
        }
        
        public triAIFCreateSalesQuotationOrderServiceAIFCreateSalesQuotationRequest(WooService.AXServices.AIFCrearPedidos.CallContext CallContext, string _encabezado, string _detalle)
        {
            this.CallContext = CallContext;
            this._encabezado = _encabezado;
            this._detalle = _detalle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="triAIFCreateSalesQuotationOrderServiceAIFCreateSalesQuotationResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class triAIFCreateSalesQuotationOrderServiceAIFCreateSalesQuotationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public triAIFCreateSalesQuotationOrderServiceAIFCreateSalesQuotationResponse()
        {
        }
        
        public triAIFCreateSalesQuotationOrderServiceAIFCreateSalesQuotationResponse(string response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="triAIFCreateSalesQuotationOrderServiceAIFBorrarPedidoRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class triAIFCreateSalesQuotationOrderServiceAIFBorrarPedidoRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public WooService.AXServices.AIFCrearPedidos.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _pedido;
        
        public triAIFCreateSalesQuotationOrderServiceAIFBorrarPedidoRequest()
        {
        }
        
        public triAIFCreateSalesQuotationOrderServiceAIFBorrarPedidoRequest(WooService.AXServices.AIFCrearPedidos.CallContext CallContext, string _pedido)
        {
            this.CallContext = CallContext;
            this._pedido = _pedido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="triAIFCreateSalesQuotationOrderServiceAIFBorrarPedidoResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class triAIFCreateSalesQuotationOrderServiceAIFBorrarPedidoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public triAIFCreateSalesQuotationOrderServiceAIFBorrarPedidoResponse()
        {
        }
        
        public triAIFCreateSalesQuotationOrderServiceAIFBorrarPedidoResponse(string response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="triAIFCreateSalesQuotationOrderServiceAIFCreateSalesOrderWEBRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class triAIFCreateSalesQuotationOrderServiceAIFCreateSalesOrderWEBRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public WooService.AXServices.AIFCrearPedidos.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _encabezado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _detalle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=2)]
        public bool _emitirFactura;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=3)]
        public bool _eliminarPedidoSiHayError;
        
        public triAIFCreateSalesQuotationOrderServiceAIFCreateSalesOrderWEBRequest()
        {
        }
        
        public triAIFCreateSalesQuotationOrderServiceAIFCreateSalesOrderWEBRequest(WooService.AXServices.AIFCrearPedidos.CallContext CallContext, string _encabezado, string _detalle, bool _emitirFactura, bool _eliminarPedidoSiHayError)
        {
            this.CallContext = CallContext;
            this._encabezado = _encabezado;
            this._detalle = _detalle;
            this._emitirFactura = _emitirFactura;
            this._eliminarPedidoSiHayError = _eliminarPedidoSiHayError;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="triAIFCreateSalesQuotationOrderServiceAIFCreateSalesOrderWEBResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class triAIFCreateSalesQuotationOrderServiceAIFCreateSalesOrderWEBResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public triAIFCreateSalesQuotationOrderServiceAIFCreateSalesOrderWEBResponse()
        {
        }
        
        public triAIFCreateSalesQuotationOrderServiceAIFCreateSalesOrderWEBResponse(string response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="triAIFCreateSalesQuotationOrderServiceAIFCreateSalesOrderRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class triAIFCreateSalesQuotationOrderServiceAIFCreateSalesOrderRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public WooService.AXServices.AIFCrearPedidos.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _encabezado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=1)]
        public string _detalle;
        
        public triAIFCreateSalesQuotationOrderServiceAIFCreateSalesOrderRequest()
        {
        }
        
        public triAIFCreateSalesQuotationOrderServiceAIFCreateSalesOrderRequest(WooService.AXServices.AIFCrearPedidos.CallContext CallContext, string _encabezado, string _detalle)
        {
            this.CallContext = CallContext;
            this._encabezado = _encabezado;
            this._detalle = _detalle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="triAIFCreateSalesQuotationOrderServiceAIFCreateSalesOrderResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class triAIFCreateSalesQuotationOrderServiceAIFCreateSalesOrderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public triAIFCreateSalesQuotationOrderServiceAIFCreateSalesOrderResponse()
        {
        }
        
        public triAIFCreateSalesQuotationOrderServiceAIFCreateSalesOrderResponse(string response)
        {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="triAIFCreateSalesQuotationOrderServiceAIFFacturarPedidoVtaRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class triAIFCreateSalesQuotationOrderServiceAIFFacturarPedidoVtaRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public WooService.AXServices.AIFCrearPedidos.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string _pedido;
        
        public triAIFCreateSalesQuotationOrderServiceAIFFacturarPedidoVtaRequest()
        {
        }
        
        public triAIFCreateSalesQuotationOrderServiceAIFFacturarPedidoVtaRequest(WooService.AXServices.AIFCrearPedidos.CallContext CallContext, string _pedido)
        {
            this.CallContext = CallContext;
            this._pedido = _pedido;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="triAIFCreateSalesQuotationOrderServiceAIFFacturarPedidoVtaResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class triAIFCreateSalesQuotationOrderServiceAIFFacturarPedidoVtaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public triAIFCreateSalesQuotationOrderServiceAIFFacturarPedidoVtaResponse()
        {
        }
        
        public triAIFCreateSalesQuotationOrderServiceAIFFacturarPedidoVtaResponse(string response)
        {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface triAIFCreateSalesQuotationOrderServiceChannel : WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class triAIFCreateSalesQuotationOrderServiceClient : System.ServiceModel.ClientBase<WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderService>, WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public triAIFCreateSalesQuotationOrderServiceClient() : 
                base(triAIFCreateSalesQuotationOrderServiceClient.GetDefaultBinding(), triAIFCreateSalesQuotationOrderServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NetTcpBinding_triAIFCreateSalesQuotationOrderService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public triAIFCreateSalesQuotationOrderServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(triAIFCreateSalesQuotationOrderServiceClient.GetBindingForEndpoint(endpointConfiguration), triAIFCreateSalesQuotationOrderServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public triAIFCreateSalesQuotationOrderServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(triAIFCreateSalesQuotationOrderServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public triAIFCreateSalesQuotationOrderServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(triAIFCreateSalesQuotationOrderServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public triAIFCreateSalesQuotationOrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFCreateSalesQuotationResponse> WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderService.AIFCreateSalesQuotationAsync(WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFCreateSalesQuotationRequest request)
        {
            return base.Channel.AIFCreateSalesQuotationAsync(request);
        }
        
        public System.Threading.Tasks.Task<WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFCreateSalesQuotationResponse> AIFCreateSalesQuotationAsync(WooService.AXServices.AIFCrearPedidos.CallContext CallContext, string _encabezado, string _detalle)
        {
            WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFCreateSalesQuotationRequest inValue = new WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFCreateSalesQuotationRequest();
            inValue.CallContext = CallContext;
            inValue._encabezado = _encabezado;
            inValue._detalle = _detalle;
            return ((WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderService)(this)).AIFCreateSalesQuotationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFBorrarPedidoResponse> WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderService.AIFBorrarPedidoAsync(WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFBorrarPedidoRequest request)
        {
            return base.Channel.AIFBorrarPedidoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFBorrarPedidoResponse> AIFBorrarPedidoAsync(WooService.AXServices.AIFCrearPedidos.CallContext CallContext, string _pedido)
        {
            WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFBorrarPedidoRequest inValue = new WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFBorrarPedidoRequest();
            inValue.CallContext = CallContext;
            inValue._pedido = _pedido;
            return ((WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderService)(this)).AIFBorrarPedidoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFCreateSalesOrderWEBResponse> WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderService.AIFCreateSalesOrderWEBAsync(WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFCreateSalesOrderWEBRequest request)
        {
            return base.Channel.AIFCreateSalesOrderWEBAsync(request);
        }
        
        public System.Threading.Tasks.Task<WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFCreateSalesOrderWEBResponse> AIFCreateSalesOrderWEBAsync(WooService.AXServices.AIFCrearPedidos.CallContext CallContext, string _encabezado, string _detalle, bool _emitirFactura, bool _eliminarPedidoSiHayError)
        {
            WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFCreateSalesOrderWEBRequest inValue = new WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFCreateSalesOrderWEBRequest();
            inValue.CallContext = CallContext;
            inValue._encabezado = _encabezado;
            inValue._detalle = _detalle;
            inValue._emitirFactura = _emitirFactura;
            inValue._eliminarPedidoSiHayError = _eliminarPedidoSiHayError;
            return ((WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderService)(this)).AIFCreateSalesOrderWEBAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFCreateSalesOrderResponse> WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderService.AIFCreateSalesOrderAsync(WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFCreateSalesOrderRequest request)
        {
            return base.Channel.AIFCreateSalesOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFCreateSalesOrderResponse> AIFCreateSalesOrderAsync(WooService.AXServices.AIFCrearPedidos.CallContext CallContext, string _encabezado, string _detalle)
        {
            WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFCreateSalesOrderRequest inValue = new WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFCreateSalesOrderRequest();
            inValue.CallContext = CallContext;
            inValue._encabezado = _encabezado;
            inValue._detalle = _detalle;
            return ((WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderService)(this)).AIFCreateSalesOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFFacturarPedidoVtaResponse> WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderService.AIFFacturarPedidoVtaAsync(WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFFacturarPedidoVtaRequest request)
        {
            return base.Channel.AIFFacturarPedidoVtaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFFacturarPedidoVtaResponse> AIFFacturarPedidoVtaAsync(WooService.AXServices.AIFCrearPedidos.CallContext CallContext, string _pedido)
        {
            WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFFacturarPedidoVtaRequest inValue = new WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderServiceAIFFacturarPedidoVtaRequest();
            inValue.CallContext = CallContext;
            inValue._pedido = _pedido;
            return ((WooService.AXServices.AIFCrearPedidos.triAIFCreateSalesQuotationOrderService)(this)).AIFFacturarPedidoVtaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_triAIFCreateSalesQuotationOrderService))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_triAIFCreateSalesQuotationOrderService))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://srvaxaos:8201/DynamicsAx/Services/triAIFCreateSalesQuotationOrderSG");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return triAIFCreateSalesQuotationOrderServiceClient.GetBindingForEndpoint(EndpointConfiguration.NetTcpBinding_triAIFCreateSalesQuotationOrderService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return triAIFCreateSalesQuotationOrderServiceClient.GetEndpointAddress(EndpointConfiguration.NetTcpBinding_triAIFCreateSalesQuotationOrderService);
        }
        
        public enum EndpointConfiguration
        {
            
            NetTcpBinding_triAIFCreateSalesQuotationOrderService,
        }
    }
}
